### ISSUE TITLE
[Feature] support graphql-config

### ISSUE THREAD

**Issue by benbender** [HoudiniGraphql/houdini#156]
Hey,

just thought it would be nice if houdini would support [Graphql-config](https://graphql-config.com/) to get the endpoint and, possibly, to configure the path where the schema is pulled to. What do you think?

**Comment by AlecAivazis** [comment]
I think its an interesting idea but I'm a bit wary to introduce/encourage yet another config file, especially one that seems to only work with CommonJS. Is there a specific tool you would like to integrate with?

**Comment by benbender** [comment]
For me it's the single-source of truth for my graphql-config. Mainly because its natively supported in [vscode-graphql](https://github.com/graphql/vscode-graphql)

**Comment by AlecAivazis** [comment]
re CommonJS, i just didn't see an esm file in their example but I might have missed it. I'm definitely in favor of adding support as long as we can easily embed the necessary scalar config and the rest of the houdini specifics

**Comment by jycouet** [comment]
Graphql-config file plays well with Houdini.
You can configure a `.graphqlrc.yaml` with something like: 
```yaml
projects:
  default:
    schema:
      - ./schema.graphql
      - ./$houdini/graphql/schema.graphql
    documents:
      - **/*.gql
      - ./$houdini/graphql/documents.gql
```
And vscode plugin will take is as usual.

---

@benbender, you would like `houdini.config.js` to be inside `.graphqlrc.yaml` with the `extension` mechanism?
I'm not sure any _"main"_ config could be taken from Graphql-config, so everything would be in the `extension`.
I understand the wish to have everything graphql in one place.
I just would like a confirmation that this is still a need?
